name: Workflow Secret
on: push
jobs:
  display_values:
    runs-on: ubuntu-latest
    steps:
      - run: 
          echo "${{secrets.DATABASE_PASSWORD}}"
          echo "${{vars.VERSION}}"
      - name: GitHub Script
        uses: actions/github-script@v7.0.1
        id: step-return
        with: 
          script: return "Mon retour";
  reuse_values:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A MODIFIER"
